server:
  port: 4000

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 1
    driver-class-name: org.h2.Driver
#  datasource:
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  messages:
    encoding: UTF-8
logging.level:
  org.hibernate.SQL: debug